### ISSUE TITLE
Using innerHTML 

### ISSUE THREAD

**Issue by ghassanmas** [fack2/SR-Books#22]
The innerHTML method has secuirty concerns :scream:, it could make your website esay hackable. 
There are always alternative to innerHTML. e.g. `textContent` or `innerText`.

https://github.com/fack2/SR-Books/blob/77f6427938fb8d24aacb06ccf68b99df606863aa/public/index.js#L58

**Comment by sara219** [comment]
#32 @ghassanmas  
DONE!
