### ISSUE TITLE
requesting site in http rather than https

### ISSUE THREAD

**Issue by ghassanmas** [fack2/SR-Books#24]
Given you request the site in `http` and the github pages (Where your website is deployed) is using `https` this cause the site not working. hence check your console error:

`Mixed Content: The page at 'https://fack2.github.io/SR-Books/' was loaded over HTTPS, but requested an insecure resource 'http://www.omdbapi.com/?t=saw&apikey=9cdd68b6'. This request has been blocked; the content must be served over HTTPS.`

https://github.com/fack2/SR-Books/blob/77f6427938fb8d24aacb06ccf68b99df606863aa/public/index.js#L24

**Comment by sara219** [comment]
@ghassanmas 
we fix that problem
